### ISSUE TITLE
Requests to locations that don't exist return the wrong error code

### ISSUE THREAD

**Issue by EmeraldSnorlax** [l1ving/fs-over-http#3]
Send a request to a location that doesn't exist (eg https://i.l1v.in/asdf/)

Expected response
---
Some variation of `404 Not Found` with a `status` of `404`

Actual response
---
`500 stat filesystem/public/asdf: no such file or directory` with a `status` of `500`

https://github.com/l1ving/fs-over-http/blob/5865251d5297ea7d2a5fca6d81b5e66bdd076004/main.go#L327 this looks like it's to blame?

**Comment by 5HT2** [comment]
I don't know how I feel about fixing this other than for "muh proper webdev REST model". I've added new notes in the README but I'm still undecided on actually printing any visible response other than a status code if there's an error.

**Comment by EmeraldSnorlax** [comment]
Not doing so *strongly* goes against conventions and will make it more difficult for others that are working against the API. Besides from the looks of it, it seems that error handling could deal with a refactor anyway...

Just returning the status code is fine, the status code contains the semantics of it anyway. Text should only really be provided if its a client error and the client has made a mistake (eg `403: You don't have permission to view /foo`)

for server errors, just sending back a vague 500 class error is the norm, and is actually preferred, in order to not accidentally send across sensitive data.

**Comment by 5HT2** [comment]
Fixed in 44cb687c08f164646d22f826a2e767df92322f50
