### ISSUE TITLE
`400 Missing 'file' or 'dir' or 'content' form` but the `file` key is present.

### ISSUE THREAD

**Issue by d1snin** [l1ving/fs-over-http#8]
![image](https://user-images.githubusercontent.com/68169685/157245875-cd346294-97ea-41a7-ab55-e97d1938faca.png)
Can I get some advice?

**Comment by 5HT2** [comment]
You're missing the @ symbol. 

The correct syntax here would be

```bash
curl -X POST https://fs.d1s.cc/pptx/presentation_sound_waves.pptx -H "Auth: $TOKEN" -F "file=@/home/d1snin/Documents/presentation_sound_waves.pptx"
```

**Comment by d1snin** [comment]
oh, thank you

**Comment by 5HT2** [comment]
Without the @ you're setting the form content to a bunch of text instead of the file.

**Comment by d1snin** [comment]
> Without the @ you're setting the form content to a bunch of text instead of the file.

I got it

**Comment by d1snin** [comment]
There is another problem:
![image](https://user-images.githubusercontent.com/68169685/157246732-94c92182-a86e-4b4d-86df-e79c44aae5ac.png)

And the file is not being served

**Comment by 5HT2** [comment]
You have to append `public` manually if you want to upload to the public folder, eg

```
curl -X POST https://fs.d1s.cc/public/pptx/presentation_sound_waves.pptx -H "Auth: $TOKEN" -F "file=@/home/d1snin/Documents/presentation_sound_waves.pptx"
```

**Comment by 5HT2** [comment]
(only when using a token)

**Comment by d1snin** [comment]
I see, can you update the `USAGE.md` then?

**Comment by 5HT2** [comment]
I'll add a note, sorry that wasn't clear.

**Comment by d1snin** [comment]
Thank you

**Comment by 5HT2** [comment]
d1854fec78b3b8e1196c4f9cdd1be323c9b77e96
